# HeadDrops Plugin
# Created by @BaconCat1
# Copyright (C) 2025 BaconCat1
# Licensed under the GNU General Public License v3.0

name: HeadDrops
version: '${version}'
main: org.bacon.headDrops.HeadDrops
api-version: '1.21'
folia-supported: true
